name: Deploy simple example to GitHub Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yml') }}

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install Dependencies
        working-directory: ./examples/simple
        run: pnpm install

      - name: Build
        working-directory: ./examples/simple
        run: pnpm build

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/simple/dist
